THEME_ID="cowboy-bebop"
THEME_NAME="Cowboy Bebop"
SYSTEM_NAME="BEBOP SYSTEM"

WALLPAPER="wallpapers/cowboy-bebop/main.png"
WALLPAPER_FIT="cover"

WALLPAPER_DEFAULT_ID="main"

WALLPAPER_VARIANTS=(
    "main|MAIN|wallpapers/cowboy-bebop/main.png|cover"
    "bebop0|BEBOP0|wallpapers/cowboy-bebop/bebop0.png|cover"
)

MONITOR="eDP-1"

BACKGROUND="#070A0D"
PANEL="#0B1117"
PANEL_ALT="#101922"

TEXT="#E8E2D5"
MUTED="#71808D"

RED="#D33A3A"
YELLOW="#D6A83C"
BLUE="#3977A8"
TEAL="#3D8177"

BORDER="#243644"
