THEME_ID="evangelion"
THEME_NAME="Neon Genesis Evangelion"
SYSTEM_NAME="NERV // MAGI CONTROL"
DUNST_TEMPLATE="config/dunst/evangelion.dunstrc.template"
HYPRLOCK_TEMPLATE="config/hyprlock/evangelion.hyprlock.conf.template"

WALLPAPER="wallpapers/evangelion/main.jpg"
WALLPAPER_FIT="cover"

WALLPAPER_DEFAULT_ID="main"

WALLPAPER_VARIANTS=(
    "main|MAIN|wallpapers/evangelion/main.jpg|cover"
)

MONITOR="eDP-1"

BACKGROUND="#050607"
PANEL="#090B0C"
PANEL_ALT="#111516"

TEXT="#D7D5CE"
MUTED="#737A77"

# NERV red
RED="#D83A2E"

# warning / LCL orange
YELLOW="#C97A32"

# EVA-01 purple
BLUE="#5C4B72"

# MAGI terminal green
TEAL="#69965D"

BORDER="#2C3233"
