DUNST_TEMPLATE="config/dunst/elden-ring.dunstrc.template"
HYPRLOCK_TEMPLATE="config/hyprlock/elden-ring.hyprlock.conf.template"

THEME_NAME="Elden Ring"
SYSTEM_NAME="THE LANDS BETWEEN"
WALLPAPER="wallpapers/elden-ring/main.jpeg"
WALLPAPER_FIT="cover"

WALLPAPER_DEFAULT_ID="main"

WALLPAPER_VARIANTS=(
    "main|MAIN|wallpapers/elden-ring/main.jpeg|cover"
)
MONITOR="eDP-1"

BACKGROUND="#05070A"
PANEL="#090C10"
PANEL_ALT="#10151B"

TEXT="#D8D2C4"
MUTED="#777D86"

RED="#9E5A3A"
YELLOW="#C9A85B"
BLUE="#657C9E"
TEAL="#8FA6B8"

BORDER="#343A43"
